import { OpenProvider } from "@/context/OpenProvider";
import type { Metadata } from "next";
import { ThemeProvider } from 'next-themes';
import "./globals.css";

export const metadata: Metadata = {
  title: "Windows Simulator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <OpenProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem>
            {children}
          </ThemeProvider>
        </OpenProvider>
      </body>
    </html>
  );
}
